name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl
        coverage: none

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Node dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: laravel-build
        path: public/build

  Run-Tests:
    needs: Setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl
        coverage: none

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: laravel-build
        path: public/build

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Prepare environment
      run: |
        cp .env.example .env
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache
        mkdir -p storage/app/public/blog
        php artisan storage:link
        touch database/database.sqlite
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env
        echo "DB_FOREIGN_KEYS=true" >> .env
        php artisan migrate

    - name: Copy test images to storage
      run: |
        cp -r tests/Fixtures/images/* storage/app/public/blog

    - name: Run tests
      run: vendor/bin/phpunit
